### ISSUE TITLE
Giddy Up Dragon Stacking

### ISSUE THREAD

**Issue by kittycat2002** [Aether-Guild/Dragons-Descent#2]
I ran into an issue relating to giddy up, I think this image explains everything.
![image](https://user-images.githubusercontent.com/11175185/205467436-5e3132e0-3126-4c1d-abe5-55127e207d98.png)
steps to reproduce:
1. select a dragon and draft it
2. right click another dragon
3. mount
[log](https://gist.github.com/HugsLibRecordKeeper/713b438da63c3274e5bfbbcd1cf9e478)

**Comment by Caaz** [comment]
Seems like a good feature

**Comment by ottersholdhands** [comment]
![RimWorldWin64_LJ2xJYYrhW](https://user-images.githubusercontent.com/61456277/205472873-5cf4925b-bb23-4388-b16b-cd96c5e6beca.png) working as intended
